### Register user
POST http://localhost:5000/api/v1/Auth/register
Content-Type: application/json

{
  "email": "joao@example.com",
  "password": "12345678"
}

### Authenticate
POST http://localhost:5000/api/v1/Auth/token
Content-Type: application/json

{
  "email": "joao@example.com",
  "password": "12345678"
}

### POST Api Key

POST http://localhost:5000/api/v1/ApiKey
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2FvQGV4YW1wbGUuY29tIiwicGxhbiI6IkZyZWUiLCJqdGkiOiI0ZWEzNTU5OC1mY2UzLTRjNDctYmJhNS0wOTIxN2Y3NDFkODYiLCJleHAiOjE3NTA4MTUyODMsImlzcyI6IlJhdGVMaW1pdEFQSSIsImF1ZCI6IlJhdGVMaW1pdENsaWVudCJ9.abPIhn-mKmVzTaRO8nn1DICdey5orsSweZcE5jbh0Aw

{
    "Name": "Test"
}
